### ISSUE TITLE
Graphics are not updated

### ISSUE THREAD

**Issue by myprefrontalcortex** [IanPeake/FatMaxxer#10]
While the data at the top are continuously updated, the graphics at the bottom stop sheet a couple of minutes.

**Comment by myprefrontalcortex** [comment]
The graphics stop updating after 2 min

**Comment by IanPeake** [comment]
Thanks. If possible, can you retrieve your logs and share them?

**Comment by myprefrontalcortex** [comment]
Hi, sorry. Just read the email.
I'd love to, but the app crashes when I want to export the logs. Opens a new issue about it a few minutes ago.
