### ISSUE TITLE
App crashes during export

### ISSUE THREAD

**Issue by myprefrontalcortex** [IanPeake/FatMaxxer#13]
Every time I try to export a log file the app crashes.

**Comment by MedTechCD** [comment]
This one seems solved for me with latest update.

**Comment by myprefrontalcortex** [comment]
Latest update here on githup or playstore?

**Comment by IanPeake** [comment]
Thanks for reporting/tracking. Email ***@***.*** for access to
latest update.

**Comment by myprefrontalcortex** [comment]
Sorry Ian. I don't understand this instruction. Email to ***@***.***?

**Comment by IanPeake** [comment]
Github apparently censors email addresses. You can find the contact email
in the README.md. Email me and I will add you to the test cohort, which
will reduce the delay in receiving new releases if you can't sideload the
APK including in the Github repo.

IanP

**Comment by myprefrontalcortex** [comment]
Cheers, will do that.
Thanks a lot!

**Comment by MedTechCD** [comment]
I meant latest here on github. Nothing availble yet on the Play Store

**Comment by myprefrontalcortex** [comment]
Ok, now the export and graphics are working.
Will close 2 issues
