### ISSUE TITLE
Graph disappears after and export not working

### ISSUE THREAD

**Issue by afxmedia** [IanPeake/FatMaxxer#16]
Just tried the latest release with a1v2 for an hour workout. Most things seem to be working except:
1.  line graph disappear after 2min
2. unable to export log. after selecting the logs to export, nothing happens. 

![fatmaxxer_line_graph_disappears](https://user-images.githubusercontent.com/16061584/122877304-0b53cc00-d369-11eb-9658-5756946334e9.jpg)

**Comment by IanPeake** [comment]
Can you please specify which version number or name you are running. Android should give you "app info" for the running app. At the very bottom you will find the version name.

**Comment by afxmedia** [comment]
Sure it's 
Version 20210621_092446.main.540708e

**Comment by IanPeake** [comment]
So we are still waiting more than 24hours for Google to push releases to
the Play Store.

Email me at the README.md address and I can give you access to the internal
test release.

IanP

**Comment by afxmedia** [comment]
sure, just sent the email

**Comment by fearby** [comment]
I am having the same problem with version 540708e - email sent to fatmaxxer@gmail.com for the playstore access.

**Comment by MedTechCD** [comment]
Still nothing on the Play Store in Belgium...

**Comment by MedTechCD** [comment]
Link is up on the Play Store now.

**Comment by afxmedia** [comment]
I can confirm that the Play Store version fixes the issue
