### ISSUE TITLE
Configuration for Notifications

### ISSUE THREAD

**Issue by MedTechCD** [IanPeake/FatMaxxer#2]
The app has now an extra option to disable the notification text body to save screen space. But when the text body is disabled, there is still a blank line. Turns out that only very little space is saved that way. The notifications on an EDGE 830 are still too intrusive hiding about 30% of the screen.

**Comment by IanPeake** [comment]
Is this still an issue for you? Believed fixed but I can't test.

**Comment by MedTechCD** [comment]
I can live with it for now but the notifications are not the handiest solution. They still take up quit some space and while the notification is displayed, it becomes difficult to swipe to the next page. That's problematic when riding an unknown course where I regularly switch between my main screen and the map.

**Comment by IanPeake** [comment]
If I understand correctly this issue is now resolved. Something more than (configurable) notifications is needed to meet your needs. Can you please close this issue and create a new one that captures this requirement.
