### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by samoramobile** [IanPeake/FatMaxxer#4]
Hi.

I try the app in 2 android smartphones, in one the app open but after 3 seconds close (Samsung A52) and in other crash immediately (Huawei Mate 20 Pro) both with android 11.

**Comment by IanPeake** [comment]
I wonder whether the crash is due to the old logging method that tries to
write to external storage... give me 24 hours and I'll do a new build.

**Comment by darren3** [comment]
This may help. "I found that setting the preferred device seemed to stop Fatmaxxer from crashing for me (Polar H10)."

https://forum.intervals.icu/t/hrv-guided-training/3436/102

**Comment by samoramobile** [comment]
How can I make this configuration, this because the application doesn't let me do anything since it closes for less than 3 seconds

**Comment by samoramobile** [comment]
The problem is that I can’t do anything, I don’t even have time to touch the screen.

https://photos.app.goo.gl/nx3m57UD2e12fcRi8

**Comment by darren3** [comment]
If the problem is related to storage as the developer suspects try giving the app Storage permissions. Here is a video explaining how. https://youtu.be/qpaa-L7eiYs

**Comment by IanPeake** [comment]
You could try with the new APK release in the Github repo. Or feel free to email me using the email address in README.md and I will add you to the tester list for earlier access to the Google Play releases. If release 39 (20210621_203459.main.9d7349b) still has the issue, I'd like to know.

**Comment by IanPeake** [comment]
Also, which version of Android are you using?

**Comment by samoramobile** [comment]
Hi,

I'm using Android version 11, I have a Huawei Mate 20 Pro and a Samsung
Galaxy a52.
This latest version is working, I'm just unlucky yesterday while testing. I
dropped my Polar H10 sensor and it stopped working, they borrowed a Wahoo
TICKR from the store, and apparently this doesn't work with the application,
I hope by the end of the week to have Polar again.
As for the possibility of being added to the beta version and having early
access, I would like to be a part and help with whatever I can.
Thank you very much

João


IanPeake ***@***.***> escreveu no dia terça, 22/06/2021 à(s)
08:06:
