### ISSUE TITLE
latest build crashes on start, debug log can't be shared

### ISSUE THREAD

**Issue by dhanek** [IanPeake/FatMaxxer#6]
I used a build from 14th June for several hours without problem, but the latest app-debug.apk crashes on start. I set permissions for storage and location.
Also I can't share the generated debug log. When I try to send it via mail or upload it I get error messages file not found or file not supported.

**Comment by fearby** [comment]
Happened to me but try enabling developer options on your phone

**Comment by fearby** [comment]
I uploaded my debug report here I think. Apologies if it is not what you wanted 
https://drive.google.com/file/d/12D8HGg02yU6kVFSZ7SYHlrYxsF_SY2G2/view?usp=drivesdk

**Comment by IanPeake** [comment]
I've fixed a bug related to this. You may like to re-test and update me.

**Comment by fearby** [comment]
> I've fixed a bug related to this. You may like to re-test and update me.

It will work now without immediately crashing. I will get a HR strap and see how it functions.

**Comment by dhanek** [comment]
With reinstall of the new version it works again, also without storage permission. Thanks for the work you put into it!
